modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"
[[mods]]
modId="mobcrossing"
version="${file.jarVersion}"
displayName="Mob Crossing"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-crossing"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Mob Crossing Mod'''
[[dependencies.mobcrossing]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mobcrossing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
