modLoader="javafml"
loaderVersion="[51,)"
license="MIT License"
[[mods]]
modId="mobcrossing"
version="${file.jarVersion}"
displayName="Mob Crossing"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-crossing"
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Mob Crossing Mod'''
[[dependencies.mobcrossing]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mobcrossing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
